### ISSUE TITLE
How to set password please ？

### ISSUE THREAD

**Issue by sunjianan9900** [SiLeader/dedis#3]
How to set password please ？

**Comment by SiLeader** [comment]
Thank you for your question.

Sorry, dedis is not supporting user and password authentication now.
I add authentication to the list of features to be implemented.

**Comment by SiLeader** [comment]
Authentication function is added. (in 0.4.1)

To use this function, write like the following, please.
```dart
await RedisClient.connect(
    'localhost',
    6379,
    db: 1,
    password: '123456789',
);
```

Thank you,
